---
AWSTemplateFormatVersion: '2010-09-09'
Description: >
  Creates an aliased A Record Set for the Network Loadbalancer associated with
  Gaming service.
  Prerequisite: A registered Domain Name and a previously defined Hosted Zone.

# ------------------------------------------


# ==========================================
Metadata: {}
# Metadata:


# ==========================================
# Parameters {}
Parameters:

  # ------------------------------------------
  # --- The Project Name
  ProjectName:
    Description: "The Name given to this Project."
    ConstraintDescription: "Name must satisfy S3 constraints."
    Type: String
    Default: "cfn-gpu-cli"
    MinLength: 3
    MaxLength: 63
    AllowedPattern:
      ^[a-zA-Z0-9.\-_]{1,255}$

  # ------------------------------------------
  # --- Route53 Particulars
  GamingDomainName:
    Description: "Gaming Domain Name"
    Type: String
    Default: "cloudemprise.net"
    AllowedPattern:
      ^(([a-zA-Z]{1})|([a-zA-Z]{1}[a-zA-Z]{1})|([a-zA-Z]{1}[0-9]{1})|([0-9]{1}[a-zA-Z]{1})|([a-zA-Z0-9][a-zA-Z0-9-_]{1,61}[a-zA-Z0-9]))\.([a-zA-Z]{2,6}|[a-zA-Z0-9-]{2,30}\.[a-zA-Z]{2,3})$
  # .............................
  GamingR53HostedZoneId:
    Description: "An Amazon Route 53 hosted zone ID"
    Type: AWS::Route53::HostedZone::Id
  # .............................
  GamingLoadBalancerDNS:
    Description: "Gaming Network Loadbalancer DNS"
    Type: String
  # .............................
  GamingLoadBalancerZoneId:
    Description: "Network Loadbalancer Hosted Zone ID"
    Type: String


# ==========================================
Conditions: {}
# Conditions:


# ==========================================
Resources:

  # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  #         ROUTE 53 RECORD SET
  # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


  # ------------------------------------------
  # --- Record Set Definition
  GamingR53RecordSet:
    Type: "AWS::Route53::RecordSet"
    # .............................
    Properties:
      Name: !Sub "${ProjectName}.${GamingDomainName}"
      Comment: "Gaming Route53 Record Set"
      Type: "A"
      HostedZoneId: !Ref GamingR53HostedZoneId
      AliasTarget:
        HostedZoneId: !Ref GamingLoadBalancerZoneId
        DNSName: !Ref GamingLoadBalancerDNS
        EvaluateTargetHealth: true


# ==========================================
Outputs: {}
# Outputs:
