---
AWSTemplateFormatVersion: '2010-09-09'
Description: >
  An EC2 Auto Scaling Group with static scaling policy for a standalone Gaming
  Implementation. Requires a Launch Template, a Target Group and a SNS
  notification topic. Two metrics are collected, i.e. GroupInServiceInstances
  and GroupTotalInstances. Notifies on all state changes.

# ------------------------------------------


# ==========================================
Metadata: {}
# Metadata:


# ==========================================
# Parameters {}
Parameters:

  # ------------------------------------------
  # --- The Project Name
  ProjectName:
    Description: "The Name given to this Project."
    ConstraintDescription: "Must satisfy S3 constraints."
    Type: String
    Default: "cfn-gpu-cli"
    MinLength: 3
    MaxLength: 11
    AllowedPattern: ^[a-zA-Z0-9.\-_]{1,255}$

  # ------------------------------------------
  # --- Public Subnet IDs
  PublicSubnetIdA:
    Description: "Public Subnet ID AZ-A"
    Type: "AWS::EC2::Subnet::Id"
  # .............................
  PublicSubnetIdB:
    Description: "Public Subnet ID AZ-B"
    Type: "AWS::EC2::Subnet::Id"
  # .............................
  PublicSubnetIdC:
    Description: "Public Subnet ID AZ-C"
    Type: "AWS::EC2::Subnet::Id"

  # ------------------------------------------
  GamingLaunchTemplateId:
    Description: "Launch Template Id"
    Type: String
  # ------------------------------------------
  GamingTargetGroupDcvArn:
    Description: "Network Loadbalancer DCV Target Group ARN"
    Type: String
  # ------------------------------------------
  GamingTargetGroupRdpArn:
    Description: "Network Loadbalancer RDP Target Group ARN"
    Type: String
  # ------------------------------------------
  GamingSNSTopicARN:
    Description: "Gaming SNS Activity Topic ARN"
    Type: String
    #Default: !Sub "arn:aws:sns:${AWS::Region}:${AWS::AccountId}:${ProjectName}-bulletin-asg-${AWS::Region}"


# ==========================================
Conditions: {}
# Conditions:


# ==========================================
Resources:

  # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  #       AUTO SCALE GROUP DEFINITION
  # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


  # ------------------------------------------
  # --- Auto Scale Group
  GamingAutoscalingGroup:
    Type: "AWS::AutoScaling::AutoScalingGroup"
    # .............................
    Properties:
      # .............................
      AutoScalingGroupName: !Sub "${ProjectName}-asg"
      LaunchTemplate:
        LaunchTemplateId: !Ref GamingLaunchTemplateId
        Version: "1"
      # .............................
      TargetGroupARNs:
        - !Ref GamingTargetGroupDcvArn
        - !Ref GamingTargetGroupRdpArn
      # .............................
      VPCZoneIdentifier:
        - !Ref PublicSubnetIdA
        - !Ref PublicSubnetIdB
        - !Ref PublicSubnetIdC
      # .............................
      Cooldown: "300"
      DesiredCapacity: "0"
      MinSize: "0"
      MaxSize: "1"
      # .............................
      HealthCheckType: "ELB"
      #HealthCheckType: "EC2"
      # default = 0
      HealthCheckGracePeriod: 150
      # .............................
      MetricsCollection:
        - Granularity: "1Minute"
          Metrics:
            - "GroupInServiceInstances"
            - "GroupTotalInstances"
      # .............................
      Tags:
        -
          Key: "Name"
          Value: !Sub "${ProjectName}-autoscale-grp"
          PropagateAtLaunch: true
      # .............................
      NotificationConfigurations:
        - NotificationTypes:
            - autoscaling:EC2_INSTANCE_LAUNCH
            - autoscaling:EC2_INSTANCE_LAUNCH_ERROR
            - autoscaling:EC2_INSTANCE_TERMINATE
            - autoscaling:EC2_INSTANCE_TERMINATE_ERROR
            - autoscaling:TEST_NOTIFICATION
          TopicARN: !Ref GamingSNSTopicARN


# ==========================================
Outputs: {}
# Outputs:
