---
AWSTemplateFormatVersion: '2010-09-09'
Description: >
  A encrypted SNS Topic with an email subscription.

# ------------------------------------------


# ==========================================
Metadata: {}
# Metadata:


# ==========================================
# Parameters {}
Parameters:

  # ------------------------------------------
  # --- The Project Name
  ProjectName:
    Description: "The Name given to this Project."
    ConstraintDescription: "Must satisfy S3 constraints."
    Type: String
    Default: "cfn-gpu-cli"
    MinLength: 3
    MaxLength: 11
    AllowedPattern: ^[a-zA-Z0-9.\-_]{1,255}$

  # ------------------------------------------
  # --- Email Endpoint Notifications
  GamingEmailAddrSNS:
    Description: "Gaming SNS Email Endpoint"
    Default: "dh.info@posteo.net"
    Type: String


# ==========================================
Conditions: {}
# Conditions:


# ==========================================
Resources:

  # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  #         SNS NOTIFICATIONS
  # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


  # ------------------------------------------
  # --- SNS Topic Definition
  GamingTopicSNS:
    Type: "AWS::SNS::Topic"
    # .............................
    Properties:
      DisplayName: !Sub "Gaming Server Notice ${AWS::Region}"
      TopicName: !Sub "${ProjectName}-bulletin-${AWS::Region}"
      # .............................
      Tags:
        -
          Key: "Name"
          Value: !Sub "${ProjectName}-bulletin-${AWS::Region}"
      # .............................
      KmsMasterKeyId: "alias/aws/sns"
      #KmsMasterKeyId: !Sub "alias/ce/kms/${AWS::Region}"


  # ------------------------------------------
  # --- SNS Subscription Definition
  GamingSubscriptionSNS:
    Type: "AWS::SNS::Subscription"
    # .............................
    Properties:
      TopicArn: !Ref GamingTopicSNS
      Endpoint: !Ref GamingEmailAddrSNS
      Protocol: "email"
      Region: !Ref AWS::Region


# ==========================================
# Outputs: {}
Outputs:

  # ------------------------------------------
  # --- SNS Topic ARN
  GamingSNSTopicARN:
    Description: "Gaming SNS Activity Topic ARN"
    Value: !Ref GamingTopicSNS
