---
AWSTemplateFormatVersion: '2010-09-09'
Description: >
  A Target Group for the Network Loadbalancer associated with the Gaming
  service. Health Checks come from a webserver running on the same EC2 instance.

# ------------------------------------------


# ==========================================
Metadata: {}
# Metadata:


# ==========================================
# Parameters {}
Parameters:

  # ------------------------------------------
  # --- The Project Name
  ProjectName:
    Description: "The Name given to this Project."
    ConstraintDescription: "Name must satisfy S3 constraints."
    Type: String
    Default: "cfn-gpu-cli"
    MinLength: 3
    MaxLength: 63
    AllowedPattern:
      ^[a-zA-Z0-9.\-_]{1,255}$

  # ------------------------------------------
  # --- AWS-Specific Parameter VPC Id
  VPCID:
    Description: "VPC to associate with load balancer"
    Type: "AWS::EC2::VPC::Id"


# ==========================================
Conditions: {}
# Conditions:


# ==========================================
Resources:

  # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  #     NETWORK LOAD BALANCER DEFINITIONS
  # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


  # ------------------------------------------
  # --- Target Group Definition
  GamingTargetGroup:
    Type: "AWS::ElasticLoadBalancingV2::TargetGroup"
    # .............................
    Properties:
      Name: !Sub "${ProjectName}-tgrp-${AWS::Region}"
      # .............................
      Tags:
        -
          Key: "Name"
          Value: "GamingTargetGroup"
      # .............................
      TargetGroupAttributes:
        -
          Key: "proxy_protocol_v2.enabled"
          Value: "false"
        - 
          Key: "deregistration_delay.connection_termination.enabled"
          Value: "false"
        -
          Key: "deregistration_delay.timeout_seconds"
          Value: "300"
      # .............................
      VpcId: !Ref VPCID
      TargetType: "instance"
      Port: 8443
      Protocol: "TCP_UDP"
      # .............................
      HealthCheckEnabled: true
      HealthCheckIntervalSeconds: 30
      HealthCheckPort: "8443"
      HealthCheckProtocol: "TCP"
      HealthCheckTimeoutSeconds: 10
      HealthyThresholdCount: 3
      UnhealthyThresholdCount: 3
      # .............................


# ==========================================
# Outputs: {}
Outputs:

  # ------------------------------------------
  # --- EC2 Target Group ARN
  GamingTargetGroupArn:
    Description: "Network Loadbalancer Target Group ARN"
    Value: !Ref GamingTargetGroup

  # ------------------------------------------
  # --- EC2 Target Group Name
  GamingTargetName:
    Description: "Network Loadbalancer Target Group Name"
    Value: !GetAtt GamingTargetGroup.TargetGroupName
