---
AWSTemplateFormatVersion: '2010-09-09'
Description: >
  Add Description Here.

# ------------------------------------------


# ==========================================
Metadata: {}
# Metadata:


# ==========================================
# Parameters {}
Parameters:

  # ------------------------------------------
  # --- The Project Name
  ProjectName:
    Description: "The Name given to this Project."
    ConstraintDescription: "Name must satisfy S3 constraints."
    Type: String
    Default: "cfn-gpu-rig-cli"
    MinLength: 3
    MaxLength: 63
    AllowedPattern:
      ^[a-zA-Z0-9.\-_]{1,255}$

  # ------------------------------------------
  # --- Pre-Configured Public EC2 instance
  PublicLtAmiId:
    Description: "Launch Template Public AMI ID"
    Type: "AWS::EC2::Image::Id"

  # ------------------------------------------
  # --- Public Security Group Resource ID
  PublicSgResourceId:
    Description: "Public Security Group ID AZ-A"
    Type: "AWS::EC2::SecurityGroup::Id"


# ==========================================
Conditions: {}
# Conditions:


# ==========================================
Resources:

  # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  #       LAUNCH TEMPLATE EC2 DEFINITION
  # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


  # ------------------------------------------
  # --- Public EC2 Instance
  PublicEC2LaunchTemplate:
    Type: "AWS::EC2::LaunchTemplate"
    # .............................
    Properties:
      # .............................
      LaunchTemplateName: !Sub "${ProjectName}-launch-template"
      # .............................
      LaunchTemplateData:
        ImageId: !Ref PublicLtAmiId
        InstanceType: "t2.micro"
        KeyName: !Sub "aws.dev.ec2.win.ssh.key.${AWS::Region}"
        Monitoring:
          Enabled: false
        SecurityGroupIds:
          - !Ref PublicSgResourceId
        # .............................
        IamInstanceProfile:
          Name: "role.ec2-usr-datascience.eu-central-1"
          #Name: !Sub "${ProjectName}-lt-iam-ec2-${AWS::Region}"
        # .............................
        MetadataOptions:
          HttpEndpoint: "enabled"
          #HttpTokens: "required"
          HttpTokens: "optional"
          HttpPutResponseHopLimit: 1
        # .............................
        InstanceMarketOptions: 
          MarketType: "spot"
          SpotOptions: 
            MaxPrice: "0.01000"
            # one-time | persistent
            SpotInstanceType: "one-time"
            #  hibernate | stop | terminate
            InstanceInterruptionBehavior: "terminate"

# ==========================================
# Outputs: {}
Outputs:

  # ------------------------------------------
  # --- Launch Template ID
  LaunchTemplateId:
    Description: "Launch Template ID"
    Value: !Ref PublicEC2LaunchTemplate
