---
AWSTemplateFormatVersion: '2010-09-09'
Description: >
  A encrypted SNS Topic with an email subscription.

# ------------------------------------------


# ==========================================
Metadata: {}
# Metadata:


# ==========================================
# Parameters {}
Parameters:

  # ------------------------------------------
  # --- The Project Name
  ProjectName:
    Description: "Name of this Openvpn project"
    ConstraintDescription: "Specify name of the project"
    Type: String
    Default: "cfn-gpu-rig-cli"
    MinLength: 3
    MaxLength: 63
    AllowedPattern:
      (?!^(\d{1,3}\.){3}\d{1,3}$)(^[a-z0-9]([a-z0-9-]*(\.[a-z0-9])?)*$(?<!\-))

  # ------------------------------------------
  # --- Email Endpoint Notifications
  EmailAddrSNS:
    Description: "Openvpn SNS Email Endpoint"
    Type: String


# ==========================================
Conditions: {}
# Conditions:


# ==========================================
Resources:

  # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  #         SNS NOTIFICATIONS
  # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


  # ------------------------------------------
  # --- SNS Topic Definition
  OpenvpnTopicSNS:
    Type: "AWS::SNS::Topic"
    # .............................
    Properties:
      DisplayName: "OpenvpnNotice"
      TopicName: !Sub "${ProjectName}-activity-notice-${AWS::Region}"
      KmsMasterKeyId: "alias/aws/sns"
      # .............................
      Tags:
        -
          Key: "Name"
          Value: "openvpn-activity-sns"

  # ------------------------------------------
  # --- SNS Subscription Definition
  OpenvpnSubscriptionSNS:
    Type: "AWS::SNS::Subscription"
    # .............................
    Properties:
      TopicArn: !Ref OpenvpnTopicSNS
      Endpoint: !Ref EmailAddrSNS
      Protocol: "email"
      Region: !Ref AWS::Region


# ==========================================
# Outputs: {}
Outputs:

  # ------------------------------------------
  # --- SNS Topic ARN
  OpenvpnSNSTopicARN:
    Description: "Openvpn SNS Activity Topic ARN"
    Value: !Ref OpenvpnTopicSNS
