---
AWSTemplateFormatVersion: '2010-09-09'
Description: >
  Add Description Here.

# ------------------------------------------


# ==========================================
Metadata: {}
# Metadata:


# ==========================================
# Parameters {}
Parameters:

  # ------------------------------------------
  # --- The Project Name
  ProjectName:
    Description: "The Name given to this Project."
    ConstraintDescription: "Name must satisfy S3 constraints."
    Type: String
    Default: "cfn-gpu-cli"
    MinLength: 3
    MaxLength: 63
    AllowedPattern:
      ^[a-zA-Z0-9.\-_]{1,255}$

  # ------------------------------------------
  # --- Pre-Configured Public EC2 instance
  PublicLtAmiId:
    Description: "Launch Template Public AMI ID"
    Type: "AWS::EC2::Image::Id"

  # ------------------------------------------
  # --- Public Security Group Resource ID
  PublicSgResourceId:
    Description: "Public Security Group ID AZ-A"
    Type: "AWS::EC2::SecurityGroup::Id"


# ==========================================
Conditions: {}
# Conditions:


# ==========================================
Resources:

  # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  #       LAUNCH TEMPLATE EC2 DEFINITION
  # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


  # ------------------------------------------
  # --- Public EC2 Instance
  GamingLaunchTemplate:
    Type: "AWS::EC2::LaunchTemplate"
    # .............................
    Properties:
      # .............................
      LaunchTemplateName: !Sub "${ProjectName}-launch-template"
      # .............................
      TagSpecifications:
        - 
          ResourceType: "launch-template"
          Tags:
            - 
              Key: "Name"
              Value: !Sub "${ProjectName}-launch-template"
      # .............................
      LaunchTemplateData:
        # .............................
        ImageId: !Ref PublicLtAmiId
        InstanceType: "t2.micro"
        #InstanceType: "g4dn.xlarge"
        # .............................
        KeyName: !Sub "aws.dev.ec2.win.ssh.key.${AWS::Region}"
        SecurityGroupIds:
          - !Ref PublicSgResourceId
        # .............................
        IamInstanceProfile:
          Name: !Sub "${ProjectName}-ec2-lt-${AWS::Region}"
        # .............................
        InstanceMarketOptions: 
          MarketType: "spot"
          SpotOptions: 
            #MaxPrice: "0.01000"
            # one-time | persistent
            SpotInstanceType: "one-time"
            #  hibernate | stop | terminate
            InstanceInterruptionBehavior: "terminate"
        # .............................
        Monitoring:
          Enabled: false
        # .............................
        MetadataOptions:
          HttpEndpoint: "enabled"
          HttpTokens: "required"
          #HttpTokens: "optional"
          HttpPutResponseHopLimit: 1
        # .............................
        #UserData:
        #  Fn::Base64: !Sub |
        #    <powershell>
        #      # Enter Commands Here.             
        #    </powershell>
        # .............................

# ==========================================
# Outputs: {}
Outputs:

  # ------------------------------------------
  # --- Launch Template ID
  GamingLaunchTemplateId:
    Description: "Launch Template ID"
    Value: !Ref GamingLaunchTemplate
