---
AWSTemplateFormatVersion: '2010-09-09'
Description: >
  Creates an aliased A Record Set for the Network Loadbalancer associated with
  Openvpn service.
  Prerequisite: A registered Domain Name and a previously defined Hosted Zone.

# ------------------------------------------


# ==========================================
Metadata: {}
# Metadata:


# ==========================================
# Parameters {}
Parameters:

  # ------------------------------------------
  # --- The Project Name
  ProjectName:
    Description: "Name of this Openvpn project"
    ConstraintDescription: "Specify name of the project"
    Type: String
    Default: "cfn-gpu-rig-cli"
    MinLength: 3
    MaxLength: 63
    AllowedPattern:
      (?!^(\d{1,3}\.){3}\d{1,3}$)(^[a-z0-9]([a-z0-9-]*(\.[a-z0-9])?)*$(?<!\-))

  # ------------------------------------------
  # --- Route53 Particulars
  OpenvpnDomainName:
    Description: "OpenVPN Domain Name"
    Type: String
    Default: "cloudemprise.net"
    AllowedPattern:
      ^(([a-zA-Z]{1})|([a-zA-Z]{1}[a-zA-Z]{1})|([a-zA-Z]{1}[0-9]{1})|([0-9]{1}[a-zA-Z]{1})|([a-zA-Z0-9][a-zA-Z0-9-_]{1,61}[a-zA-Z0-9]))\.([a-zA-Z]{2,6}|[a-zA-Z0-9-]{2,30}\.[a-zA-Z]{2,3})$
  # .............................
  OpenvpnR53HostedZoneId:
    Description: "An Amazon Route 53 hosted zone ID"
    Type: AWS::Route53::HostedZone::Id
  # .............................
  OpenvpnLoadBalancerDNS:
    Description: "OpenVPN Network Loadbalancer DNS"
    Type: String
  # .............................
  OpenvpnLoadBalancerZoneId:
    Description: "Network Loadbalancer Hosted Zone ID"
    Type: String


# ==========================================
Conditions: {}
# Conditions:


# ==========================================
Resources:

  # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  #         ROUTE 53 RECORD SET
  # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


  # ------------------------------------------
  # --- Record Set Definition
  OpenvpnR53RecordSet:
    Type: "AWS::Route53::RecordSet"
    # .............................
    Properties:
      Name: !Sub "${ProjectName}.${OpenvpnDomainName}"
      Comment: "Openvpn Route53 Record Set"
      Type: "A"
      HostedZoneId: !Ref OpenvpnR53HostedZoneId
      AliasTarget:
        HostedZoneId: !Ref OpenvpnLoadBalancerZoneId
        DNSName: !Ref OpenvpnLoadBalancerDNS
        EvaluateTargetHealth: true


# ==========================================
Outputs: {}
# Outputs:
