---
AWSTemplateFormatVersion: '2010-09-09'
Description: >
  A VPC declaration comprising a public and private subnet, spaning two
  availability zones. The following auxillary components are included here:

  Public & Private Route Tables.
  An Internet Gatway.
  A NAT Gateway.

  Note that the NAT Gateway is only active during Stage2 of the build process.

  CIDR Allocations:

  Public Subnet Total      : 10.0.128.0/18
  Availability Zone A CIDR : 10.0.128.0/20
  Availability Zone B CIDR : 10.0.144.0/20
  Availability Zone C CIDR : 10.0.160.0/20


  Private Subnet Total     : 10.0.0.0/17
  Availability Zone A CIDR : 10.0.0.0/19
  Availability Zone B CIDR : 10.0.32.0/19
  Availability Zone C CIDR : 10.0.64.0/19


# ------------------------------------------


# ==========================================
Metadata: {}
# Metadata:


# ==========================================
# Parameters {}
Parameters:

  # ------------------------------------------
  # --- The Project Name
  ProjectName:
    Description: "The Name given to this Project."
    ConstraintDescription: "Must satisfy S3 constraints."
    Type: String
    Default: "cfn-gpu-cli"
    MinLength: 3
    MaxLength: 11
    AllowedPattern: ^[a-zA-Z0-9.\-_]{1,255}$

  # ------------------------------------------
  # --- Stack Build Stage Indicator
  #BuildStep:
  #  Description: "Specify the Stage of the Build"
  #  Type: String
  #  Default: "stage1"


# ==========================================
Conditions: {}
#Conditions:
#  CreateResourcesStage1: !Equals [ !Ref BuildStep, "stage1"]
#  CreateResourcesStage2: !Equals [!Ref BuildStep, "stage2"]
#  CreateResourcesStage3: !Equals [!Ref BuildStep, "stage3"]


# ==========================================
Resources:

  # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  #         TOP LEVEL CIDR DEFINITION
  # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


  # ------------------------------------------
  # --- VPC Definition
  VPC:
    Type: "AWS::EC2::VPC"
    # .............................
    Properties:
      CidrBlock: "10.0.0.0/16"
      EnableDnsHostnames: true
      EnableDnsSupport: true
      Tags:
        - Key: "Name"
          Value:
            !Sub "${ProjectName}-vpc"


  # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  #         SUBNET DEFINITIONS
  # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  # ------------------------------------------
  # --- AZ-A Public Subnet
  PublicSubnetA:
    Type: "AWS::EC2::Subnet"
    # .............................
    Properties:
      CidrBlock: "10.0.128.0/20"
      MapPublicIpOnLaunch: true
      VpcId: !Ref VPC
      AvailabilityZone: !Select [ "0", !GetAZs ]
      Tags:
        - Key: "Name"
          Value:
            !Sub "${ProjectName}-PubSubnetA"

  # ------------------------------------------
  # --- AZ-B Public Subnet
  PublicSubnetB:
    Type: "AWS::EC2::Subnet"
    # .............................
    Properties:
      CidrBlock: "10.0.144.0/20"
      MapPublicIpOnLaunch: true
      VpcId: !Ref VPC
      AvailabilityZone: !Select [ "1", !GetAZs ]
      Tags:
        - Key: "Name"
          Value:
            !Sub "${ProjectName}-PubSubnetB"

  # ------------------------------------------
  # --- AZ-C Public Subnet
  PublicSubnetC:
    Type: "AWS::EC2::Subnet"
    # .............................
    Properties:
      CidrBlock: "10.0.160.0/20"
      MapPublicIpOnLaunch: true
      VpcId: !Ref VPC
      AvailabilityZone: !Select [ "2", !GetAZs ]
      Tags:
        - Key: "Name"
          Value:
            !Sub "${ProjectName}-PubSubnetC"

  # ------------------------------------------
  # --- AZ1 Private Subnet
  PrivateSubnetA:
    Type: "AWS::EC2::Subnet"
    # .............................
    Properties:
      CidrBlock: "10.0.0.0/19"
      MapPublicIpOnLaunch: false
      VpcId: !Ref VPC
      AvailabilityZone: !Select [ "0", !GetAZs ]
      Tags:
        - Key: "Name"
          Value:
            !Sub "${ProjectName}-PrivSubnetA"

  # ------------------------------------------
  # --- AZ-B Private Subnet
  PrivateSubnetB:
    Type: "AWS::EC2::Subnet"
    # .............................
    Properties:
      CidrBlock: "10.0.32.0/19"
      MapPublicIpOnLaunch: false
      VpcId: !Ref VPC
      AvailabilityZone: !Select [ "1", !GetAZs ]
      Tags:
        - Key: "Name"
          Value:
            !Sub "${ProjectName}-PrivSubnetB"

  # ------------------------------------------
  # --- AZ-C Private Subnet
  PrivateSubnetC:
    Type: "AWS::EC2::Subnet"
    # .............................
    Properties:
      CidrBlock: "10.0.64.0/19"
      MapPublicIpOnLaunch: false
      VpcId: !Ref VPC
      AvailabilityZone: !Select [ "2", !GetAZs ]
      Tags:
        - Key: "Name"
          Value:
            !Sub "${ProjectName}-PrivSubnetC"


  # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  #         ROUTE TABLE DEFINITIONS
  # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  # ------------------------------------------
  # --- Public Route Table
  RouteTablePublic:
    Type: "AWS::EC2::RouteTable"
    # .............................
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: "Name"
          Value:
            !Sub "${ProjectName}-PubRoute"

  # ------------------------------------------
  RouteTablePublicAssociationA:
    Type: "AWS::EC2::SubnetRouteTableAssociation"
    # .............................
    Properties:
      RouteTableId: !Ref RouteTablePublic
      SubnetId: !Ref PublicSubnetA

  # ------------------------------------------
  RouteTablePublicAssociationB:
    Type: "AWS::EC2::SubnetRouteTableAssociation"
    # .............................
    Properties:
      RouteTableId: !Ref RouteTablePublic
      SubnetId: !Ref PublicSubnetB

  # ------------------------------------------
  RouteTablePublicAssociationC:
    Type: "AWS::EC2::SubnetRouteTableAssociation"
    # .............................
    Properties:
      RouteTableId: !Ref RouteTablePublic
      SubnetId: !Ref PublicSubnetC

  # ------------------------------------------
  RouteTablePublicRoute0:
    Type: "AWS::EC2::Route"
    # .............................
    Properties:
      DestinationCidrBlock: "0.0.0.0/0"
      RouteTableId: !Ref RouteTablePublic
      GatewayId: !Ref Igw


  # ------------------------------------------
  # --- Private A Route Table
  RouteTablePrivateA:
    Type: "AWS::EC2::RouteTable"
    # .............................
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: "Name"
          Value:
            !Sub "${ProjectName}-PrivRouteA"

  # ------------------------------------------
  RouteTablePrivateAAssociation1:
    Type: "AWS::EC2::SubnetRouteTableAssociation"
    # .............................
    Properties:
      RouteTableId: !Ref RouteTablePrivateA
      SubnetId: !Ref PrivateSubnetA

  # ------------------------------------------
  # --- Private B Route Table
  RouteTablePrivateB:
    Type: "AWS::EC2::RouteTable"
    # .............................
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: "Name"
          Value:
            !Sub "${ProjectName}-PrivRouteB"
  # ------------------------------------------
  RouteTablePrivateBAssociation1:
    Type: "AWS::EC2::SubnetRouteTableAssociation"
    # .............................
    Properties:
      RouteTableId: !Ref RouteTablePrivateB
      SubnetId: !Ref PrivateSubnetB

  # ------------------------------------------
  # --- Private C Route Table
  RouteTablePrivateC:
    Type: "AWS::EC2::RouteTable"
    # .............................
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: "Name"
          Value:
            !Sub "${ProjectName}-PrivRouteC"
  # ------------------------------------------
  RouteTablePrivateCAssociation1:
    Type: "AWS::EC2::SubnetRouteTableAssociation"
    # .............................
    Properties:
      RouteTableId: !Ref RouteTablePrivateC
      SubnetId: !Ref PrivateSubnetC


  # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  #         GATEWAY DEFINITIONS
  # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  # ------------------------------------------
  # --- Internet Gateway
  Igw:
    Type: "AWS::EC2::InternetGateway"
    # .............................
    Properties: {}

  # ------------------------------------------
  # --- Internet Gateway Attachment
  IGWAttachment:
    Type: "AWS::EC2::VPCGatewayAttachment"
    # .............................
    Properties:
      VpcId: !Ref VPC
      InternetGatewayId: !Ref Igw


# ==========================================
# Outputs: {}
Outputs:

  # ------------------------------------------
  # ---Top Level VPCID Export
  VPCID:
    Description: "VPC ID"
    Value: !Ref VPC

  # ------------------------------------------
  # ---Public Subnet AZ-A Export
  PublicSubnetIdA:
    Description: "Public Subnet ID AZ-A"
    Value: !Ref PublicSubnetA

  # ------------------------------------------
  # ---Public Subnet AZ-B Export
  PublicSubnetIdB:
    Description: "Public Subnet ID AZ-B"
    Value: !Ref PublicSubnetB

  # ------------------------------------------
  # ---Public Subnet AZ-C Export
  PublicSubnetIdC:
    Description: "Public Subnet ID AZ-C"
    Value: !Ref PublicSubnetC

  # ------------------------------------------
  # ---Private Subnet AZ-A Export
  PrivateSubnetIdA:
    Description: "Private Subnet ID AZ-A"
    Value: !Ref PrivateSubnetA

  # ------------------------------------------
  # ---Private Subnet AZ-B Export
  PrivateSubnetIdB:
    Description: "Private Subnet ID AZ-B"
    Value: !Ref PrivateSubnetB

  # ------------------------------------------
  # ---Private Subnet AZ-C Export
  PrivateSubnetIdC:
    Description: "Private Subnet ID AZ-C"
    Value: !Ref PrivateSubnetC