---
AWSTemplateFormatVersion: '2010-09-09'
Description: >
  Two Cloudwatch metrics from the AWS/AutoScaling Namespace are used to create
  Alarms for Gaming Implementation. These monitor the number of instances in
  each out-of-service and in-service state.

# ------------------------------------------


# ==========================================
Metadata: {}
# Metadata:


# ==========================================
# Parameters {}
Parameters:

  # ------------------------------------------
  # --- The Project Name
  ProjectName:
    Description: "The Name given to this Project."
    ConstraintDescription: "Name must satisfy S3 constraints."
    Type: String
    Default: "cfn-gpu-cli"
    MinLength: 3
    MaxLength: 63
    AllowedPattern:
      ^[a-zA-Z0-9.\-_]{1,255}$

  # ------------------------------------------
  # --- SNS Topic ARN
  GamingSNSTopicARN:
    Description: "Gaming SNS Activity Topic ARN"
    Type: String


# ==========================================
Conditions: {}
# Conditions:


# ==========================================
Resources:

  # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  #       CLOUDWATCH NOTIFICATIONS
  # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


  # ------------------------------------------
  # --- CloudWatch Alarm Out of Service Definition
  GamingOutOfServiceAlarm:
    Type: "AWS::CloudWatch::Alarm"
    # .............................
    Properties:
      # .............................
      AlarmName: !Sub "${ProjectName}-OutOfService"
      AlarmDescription: "Gaming Cloudwatch Alarm: Out of Service"
      # .............................
      ActionsEnabled: true
      AlarmActions:
        - !Ref GamingSNSTopicARN
      # .............................
      Namespace: "AWS/AutoScaling"
      MetricName: "GroupInServiceInstances"
      Statistic: "Maximum"
      # .............................
      TreatMissingData: "missing"
      ComparisonOperator: "LessThanThreshold"
      # .............................
      EvaluationPeriods: 5
      Threshold: 1
      Period: 60
      # .............................
      Dimensions:
        -
          Name: "AutoScalingGroupName"
          Value: !Sub "${ProjectName}-autoscale-group"

  # ------------------------------------------
  # --- CloudWatch Alarm In Service Definition
  GamingInServiceAlarm:
    Type: "AWS::CloudWatch::Alarm"
    # .............................
    Properties:
      # .............................
      AlarmName: !Sub "${ProjectName}-InService"
      AlarmDescription: "Gaming Cloudwatch Alarm: In Service"
      # .............................
      ActionsEnabled: true
      AlarmActions:
        - !Ref GamingSNSTopicARN
      # .............................
      Namespace: "AWS/AutoScaling"
      MetricName: "GroupInServiceInstances"
      Statistic: "Minimum"
      # .............................
      TreatMissingData: "missing"
      ComparisonOperator: "GreaterThanThreshold"
      # .............................
      EvaluationPeriods: 3
      Threshold: 0
      Period: 60
      # .............................
      Dimensions:
        -
          Name: "AutoScalingGroupName"
          Value: !Sub "${ProjectName}-autoscale-group"


# ==========================================
Outputs: {}
# Outputs:

# --- Cloudwatch Dimension values
# ------------------------------------------
#  LoadBalanerValue:
#    Description: Launch Template ID
#    Value: !Select [5, !Split [":", !Ref GamingLoadBalancerARN]]
#    Value: !Select [3, !Split ["/", !Select [5, !Split [":", !Ref GamingLoadBalancerARN]]]]
#    Value: !Select [3, !Split ["/", !Ref GamingLoadBalancerARN]]
#    Value: !Join ["/", ["net", !Ref GamingLoadBalancerName, !Select [3, !Split ["/", !Ref GamingLoadBalancerARN]]]]
# ------------------------------------------
#  TargetGroupValue:
#    Description: Launch Template ID
#    Value: !Select [5, !Split [":", !Ref GamingTargetGroupARN]]
# ------------------------------------------
