---
AWSTemplateFormatVersion: '2010-09-09'
Description: >
  An EC2 Auto Scaling Group with static scaling policy for a standalone Gaming
  Implementation. Requires a Launch Template, a Target Group and a SNS
  notification topic. Two metrics are collected, i.e. GroupInServiceInstances
  and GroupTotalInstances. Notifies on all state changes.

# ------------------------------------------


# ==========================================
Metadata: {}
# Metadata:


# ==========================================
# Parameters {}
Parameters:

  # ------------------------------------------
  # --- The Project Name
  ProjectName:
    Description: "The Name given to this Project."
    ConstraintDescription: "Name must satisfy S3 constraints."
    Type: String
    Default: "cfn-gpu-cli"
    MinLength: 3
    MaxLength: 63
    AllowedPattern:
      ^[a-zA-Z0-9.\-_]{1,255}$

  # ------------------------------------------
  # --- Public Subnet IDs
  PublicSubnetIdA:
    Description: "Public Subnet ID AZ-A"
    Type: "AWS::EC2::Subnet::Id"
  # .............................
  PublicSubnetIdB:
    Description: "Public Subnet ID AZ-B"
    Type: "AWS::EC2::Subnet::Id"
  # .............................
  PublicSubnetIdC:
    Description: "Public Subnet ID AZ-C"
    Type: "AWS::EC2::Subnet::Id"

  # ------------------------------------------
  LaunchTemplateIdASG:
    Description: "Launch Template Id AutoScalingGroup"
    Type: String
  # ------------------------------------------
  TargetGroupArnNLB:
    Description: "Network Loadbalancer Target Group ARN"
    Type: String
  # ------------------------------------------
  GamingSNSTopicARN:
    Description: "Gaming SNS Activity Topic ARN"
    Type: String


# ==========================================
Conditions: {}
# Conditions:


# ==========================================
Resources:

  # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  #       AUTO SCALE GROUP DEFINITION
  # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


  # ------------------------------------------
  # --- Auto Scale Group
  GamingEC2AutoScaleGrp:
    Type: "AWS::AutoScaling::AutoScalingGroup"
    # .............................
    Properties:
      # .............................
      AutoScalingGroupName: !Sub "${ProjectName}-autoscale-group"
      LaunchTemplate:
        LaunchTemplateId: !Ref LaunchTemplateIdASG
        Version: "1"
      # .............................
      Tags:
        -
          Key: "Name"
          Value: !Sub "${ProjectName}-autoscale-grp"
          PropagateAtLaunch: true
      # .............................
      VPCZoneIdentifier:
        - !Ref PublicSubnetIdA
        - !Ref PublicSubnetIdB
        - !Ref PublicSubnetIdC
      # .............................
      Cooldown: "300"
      DesiredCapacity: "1"
      MinSize: "1"
      MaxSize: "1"
      # .............................
      #HealthCheckType: "ELB"
      HealthCheckType: "EC2"
      HealthCheckGracePeriod: 300
      # .............................
      TargetGroupARNs:
        - !Ref TargetGroupArnNLB
      # .............................
      MetricsCollection:
        - Granularity: "1Minute"
          Metrics:
            - "GroupInServiceInstances"
            - "GroupTotalInstances"
      # .............................
      NotificationConfigurations:
        - NotificationTypes:
            - autoscaling:EC2_INSTANCE_LAUNCH
            - autoscaling:EC2_INSTANCE_LAUNCH_ERROR
            - autoscaling:EC2_INSTANCE_TERMINATE
            - autoscaling:EC2_INSTANCE_TERMINATE_ERROR
            - autoscaling:TEST_NOTIFICATION
          TopicARN: !Ref GamingSNSTopicARN


# ==========================================
Outputs: {}
# Outputs:
