---
AWSTemplateFormatVersion: '2010-09-09'
Description: >
  Add Description Here.

# ------------------------------------------


# ==========================================
Metadata: {}
# Metadata:


# ==========================================
# Parameters {}
Parameters:

# ==========================================
# Parameters {}
Parameters:

  # ------------------------------------------
  # --- The Project Name
  ProjectName:
    Description: "The Name given to this Project."
    ConstraintDescription: "Must satisfy S3 constraints."
    Type: String
    Default: "cfn-gpu-cli"
    MinLength: 3
    MaxLength: 11
    AllowedPattern: ^[a-zA-Z0-9.\-_]{1,255}$

  # ------------------------------------------
  # --- Launch Template AMI
  LaunchTemplateAmiId:
    Description: "Launch Template AMI ID"
    Type: "AWS::EC2::Image::Id"

  # ------------------------------------------
  # --- Public Security Group Resource ID
  PublicSgResourceId:
    Description: "Public Security Group"
    Type: "AWS::EC2::SecurityGroup::Id"

  # ------------------------------------------
  # --- Public Subnet ID
  PublicSubnetIdA:
    Description: "Public Subnet ID AZ-A"
    Type: "AWS::EC2::Subnet::Id"

  # ------------------------------------------
  # --- Public Subnet ID
  PublicSubnetIdB:
    Description: "Public Subnet ID AZ-B"
    Type: "AWS::EC2::Subnet::Id"

  # ------------------------------------------
  # --- Public Subnet ID
  PublicSubnetIdC:
    Description: "Public Subnet ID AZ-C"
    Type: "AWS::EC2::Subnet::Id"

  # ------------------------------------------
  # --- Duration of EC2 Spot Request
  SpotBlockDuration:
    Description: "Duration of EC2 Spot Request"
    ConstraintDescription: "Value must be a multiple of 60."
    Type: String
    Default: "60"

# ==========================================
Conditions: {}
# Conditions:


# ==========================================
Resources:

  # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  #       LAUNCH TEMPLATE EC2 DEFINITION
  # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


  # ------------------------------------------
  # --- Public EC2 Instance
  GamingLaunchTemplate:
    Type: "AWS::EC2::LaunchTemplate"
    # .............................
    Properties:
      # .............................
      LaunchTemplateName: !Sub "${ProjectName}-lt-asg"
      # .............................
      TagSpecifications:
        - 
          ResourceType: "launch-template"
          Tags:
            - 
              Key: "Name"
              Value: !Sub "${ProjectName}-lt-asg"
      # .............................
      LaunchTemplateData:
        # .............................
        ImageId: !Ref LaunchTemplateAmiId
        InstanceType: "t2.micro"
        #InstanceType: "g4dn.xlarge"
        # .............................
        KeyName: !Sub "aws.dev.ec2.win.ssh.key.${AWS::Region}"
        SecurityGroupIds:
          - !Ref PublicSgResourceId
        # .............................
        IamInstanceProfile:
          Name: !Sub "${ProjectName}-ec2-lt-${AWS::Region}"
        # .............................
        InstanceMarketOptions: 
          MarketType: "spot"
          SpotOptions:
            BlockDurationMinutes: !Ref SpotBlockDuration
            # one-time | persistent
            SpotInstanceType: "persistent"
            #  hibernate | stop | terminate
            InstanceInterruptionBehavior: "stop"
            # g4d.xlarge ~ 0.4
            #MaxPrice: "0.01000"
        # .............................
        Monitoring:
          Enabled: false
        # .............................
        MetadataOptions:
          HttpEndpoint: "enabled"
          HttpTokens: "required"
          #HttpTokens: "optional"
          HttpPutResponseHopLimit: 1
        # .............................
        UserData:
          Fn::Base64: !Sub |
            <powershell>
              # ___________________________
              # PROJECT VARIABLES
              # ^^^^^^^^^^^^^^^^^^^^^^^^^^^
              $NameOfProject = "cfn-gpu-cli"
              $NameOfProjBucket = "proj-cfn-gpu-cli-eu-central-1"
              # ^^^^^^^^^^^^^^^^^^^^^^^^^^^

              # ___________________________
              # Install Steam
              # ^^^^^^^^^^^^^^^^^^^^^^^^^^^
              # create sub directory 
              $SteamFilePath = "C:\$NameOfProjBucket\steam"
              New-Item $SteamFilePath -ItemType "directory" -Force
              # download installer
              $Url = 'https://cdn.cloudflare.steamstatic.com/client/installer/SteamSetup.exe'
              $SteamFileNameFull = Join-Path $SteamFilePath $(Split-Path -Path $Url -Leaf)
              Invoke-WebRequest -Uri $Url -OutFile $SteamFileNameFull
              # install passive
              Start-Process -NoNewWindow -FilePath $SteamFileNameFull -ArgumentList '/S' -Wait
            </powershell>
        # .............................

# ==========================================
# Outputs: {}
Outputs:

  # ------------------------------------------
  # --- Launch Template ID
  GamingLaunchTemplateId:
    Description: "Launch Template ID"
    Value: !Ref GamingLaunchTemplate
