---
AWSTemplateFormatVersion: '2010-09-09'
Description: >
  Add Description Here.

# ------------------------------------------


# ==========================================
Metadata: {}
# Metadata:


# ==========================================
# Parameters {}
Parameters:

  # ------------------------------------------
  # --- The Project Name
  ProjectName:
    Description: "The Name given to this Project."
    ConstraintDescription: "Name must satisfy S3 constraints."
    Type: String
    Default: "cfn-gpu-rig-cli"
    MinLength: 3
    MaxLength: 63
    AllowedPattern:
      ^[a-zA-Z0-9.\-_]{1,255}$

  # ------------------------------------------
  # --- AMI for EC2 instance
  PublicAmiId:
    Description: "Public AMI ID"
    Type: "AWS::EC2::Image::Id"

  # ------------------------------------------
  # --- Public Subnet ID
  PublicSubnetIdA:
    Description: "Public Subnet ID AZ-A"
    Type: "AWS::EC2::Subnet::Id"

  # ------------------------------------------
  # --- Public Subnet ID
  PublicSubnetIdB:
    Description: "Public Subnet ID AZ-B"
    Type: "AWS::EC2::Subnet::Id"

  # ------------------------------------------
  # --- Public Security Group Resource ID
  PublicSgResourceId:
    Description: "Public Security Group ID AZ-A"
    Type: "AWS::EC2::SecurityGroup::Id"


# ==========================================
Conditions: {}
# Conditions:


# ==========================================
Resources:

  # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  #         PUBLIC EC2 DEFINITION
  # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


  # ------------------------------------------
  # --- Public EC2 Instance
  PublicEC2Instance:
    Type: "AWS::EC2::Instance"
    # .............................
    Properties:
      # .............................
      Tags:
        -
          Key: "Name"
          Value: !Sub "${ProjectName}-gpu-build"
      # .............................
      AvailabilityZone: !Select [ "0", !GetAZs ]
        #'Fn::Select':
          #- '0'
          #- 'Fn::GetAZs':
              #Ref: 'AWS::Region'
      # .............................
      BlockDeviceMappings:
        -
          DeviceName: "/dev/sda1"
          Ebs:
            Encrypted: false
            # VolumeSize: 512
            VolumeSize: 50
            VolumeType: "gp2"
            DeleteOnTermination: true
      # .............................
      DisableApiTermination: false
      EbsOptimized: false
      EnclaveOptions: 
        Enabled: false
      HibernationOptions: 
        Configured: false
      Monitoring: false
      SourceDestCheck: true
      Tenancy: "default"
      # .............................
      #IamInstanceProfile: !Sub "${ProjectName}-pub-iam-ec2-${AWS::Region}"
      #IamInstanceProfile: "role.ec2-usr-datascience.eu-central-1"
      IamInstanceProfile: "role.ec2-usr-pwr"
      ImageId: !Ref PublicAmiId
      InstanceType: "t2.micro"
      #InstanceType: "g4dn.xlarge"
      KeyName: !Sub "aws.dev.ec2.win.ssh.key.${AWS::Region}"
      # .............................
      #SubnetId: !Ref PublicSubnetIdA
      #SecurityGroupIds: 
      #  - !Ref PublicSgResourceId
      NetworkInterfaces:
        -
          Description: "Primary Public NIC"
          DeleteOnTermination: true
          DeviceIndex: "0"
          PrivateIpAddress: "10.0.128.10"
          #PrivateIpAddress: "10.0.144.10"
          SubnetId: !Ref PublicSubnetIdA
          GroupSet:
            - !Ref PublicSgResourceId
      # .............................
      #UserData:
      #  Fn::Base64:
      #      <powershell>
      #          Copy-S3Object -BucketName depot.ce-windows -KeyPrefix shared -LocalFolder "C:\Users\Administrator\Downloads" -Region eu-central-1
      #          Start-Process msiexec.exe -Wait -ArgumentList '/I C:\Users\Administrator\Downloads\awscli\AWSCLIV2.msi /passive'
      #          Start-Process msiexec.exe -Wait -ArgumentList '/I "C:\Users\Administrator\Downloads\firefox\install\Firefox Setup 78.9.0esr.msi" /passive'
      #      </powershell>
      # .............................



# ==========================================
# Outputs: {}
Outputs:

  # ------------------------------------------
  # --- Public Instance ID
  PubEC2InstanceId:
    Description: "Public Build Instance ID"
    Value: !Ref PublicEC2Instance
