---
AWSTemplateFormatVersion: '2010-09-09'
Description: >
  Add Description Here.

# ------------------------------------------


# ==========================================
Metadata: {}
# Metadata:


# ==========================================
# Parameters {}
Parameters:

  # ------------------------------------------
  # --- The Project Name
  ProjectName:
    Description: "Name of this project"
    ConstraintDescription: "Specify name of the project"
    Type: String
    Default: "cfn-gpu-rig-cli"
    MinLength: 3
    MaxLength: 63
    AllowedPattern:
      (?!^(\d{1,3}\.){3}\d{1,3}$)(^[a-z0-9]([a-z0-9-]*(\.[a-z0-9])?)*$(?<!\-))

  # ------------------------------------------
  # --- AMI for EC2 instance
  PublicAmiId:
    Description: "Public AMI ID"
    Type: "AWS::EC2::Image::Id"

  # ------------------------------------------
  # --- Public Subnet ID
  PublicSubnetIdA:
    Description: "Public Subnet ID AZ-A"
    Type: "AWS::EC2::Subnet::Id"

  # ------------------------------------------
  # --- Public Security Group Resource ID
  PublicSgResourceId:
    Description: "Public Security Group ID AZ-A"
    Type: "AWS::EC2::SecurityGroup::Id"


# ==========================================
Conditions: {}
# Conditions:


# ==========================================
Resources:

  # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  #         PUBLIC EC2 DEFINITION
  # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


  # ------------------------------------------
  # --- Public EC2 Instance
  PublicEC2Instance:
    Type: "AWS::EC2::Instance"
    # .............................
    Properties:
      # .............................
      Tags:
        -
          Key: "Name"
          Value: !Sub "${ProjectName}-gaming-pub"
      # .............................
      AvailabilityZone: !Select [ "0", !GetAZs ]
        #'Fn::Select':
          #- '0'
          #- 'Fn::GetAZs':
              #Ref: 'AWS::Region'
      # .............................
      BlockDeviceMappings:
        -
          DeviceName: "/dev/sda1"
          Ebs:
            Encrypted: false
            VolumeSize: 512
            VolumeType: "gp2"
            DeleteOnTermination: true
      # .............................
      DisableApiTermination: false
      EbsOptimized: false
      EnclaveOptions: 
        Enabled: false
      HibernationOptions: 
        Configured: false
      Monitoring: false
      SourceDestCheck: true
      Tenancy: "default"
      # .............................
      IamInstanceProfile: !Sub "${ProjectName}-pub-iam-ec2-${AWS::Region}"
      ImageId: !Ref PublicAmiId
      InstanceType: "t2.micro"
      #InstanceType: "g4dn.xlarge"
      KeyName: !Sub "aws.dev.ec2.win.ssh.key.${AWS::Region}"
      # .............................
      NetworkInterfaces:
        -
          Description: "Primary Public NIC"
          DeleteOnTermination: true
          DeviceIndex: "0"
          PrivateIpAddress: "10.0.128.10"
          SubnetId: !Ref PublicSubnetIdA
          GroupSet:
            - !Ref PublicSgResourceId
      # .............................
      UserData:
        Fn::Base64:
          !Sub |
            <powershell>

            </powershell>
    # .............................



# ==========================================
# Outputs: {}
Outputs:

  # ------------------------------------------
  # --- Public Instance ID
  PubEC2InstanceId:
    Description: "Public Instance ID"
    Value: !Ref PublicEC2Instance
